# Generated by Django 5.0.3 on 2024-12-19 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designer_name", models.CharField(max_length=100)),
                ("contact", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="designer_profiles/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filter_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        choices=[
                            ("1000 TO 2000", "1000 TO 10000"),
                            ("10000 TO 20000", "10000 TO 20000"),
                            ("20000 TO 30000", "20000 TO 30000"),
                            ("30000 TO 40000", "30000 TO 40000"),
                            ("40000 TO 50000", "40000 TO 50000"),
                        ],
                        max_length=60,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="sample_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "status",
                    models.CharField(
                        choices=[("Publish", "Publish"), ("Draft", "Draft")],
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("information", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store_app.category",
                    ),
                ),
                (
                    "colour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store_app.color",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design_name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("front_image", models.ImageField(upload_to="design_images/")),
                (
                    "back_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="design_images/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Submitted",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store_app.category",
                    ),
                ),
                (
                    "designer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="store_app.designer",
                    ),
                ),
                (
                    "sample_images",
                    models.ManyToManyField(blank=True, to="store_app.sampleimage"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("last", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=150, null=True)),
                ("mobile", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=50, unique=True
                    ),
                ),
                ("product", models.CharField(default="", max_length=1000)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Design"),
                            (3, "Fusing"),
                            (4, "Making"),
                            (5, "Printing"),
                            (6, "Dispatch"),
                            (7, "Delivery"),
                        ],
                        default=1,
                    ),
                ),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                ("quantity", models.IntegerField()),
                ("phone", models.IntegerField()),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("product_description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
