# Generated by Django 5.0.3 on 2024-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designer",
            name="role_p",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Design"),
                    (3, "Fusing"),
                    (4, "Making"),
                    (5, "Printing"),
                    (6, "Dispatch"),
                    (7, "Delivery"),
                ],
                default=1,
            ),
        ),
    ]
