# Generated by Django 5.0.3 on 2024-12-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store_app", "0002_designer_role_p"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designer",
            name="role_p",
            field=models.IntegerField(
                choices=[
                    (1, "Design"),
                    (2, "Fusing"),
                    (3, "Making"),
                    (4, "Printing"),
                    (5, "Dispatch"),
                    (6, "Delivery"),
                ],
                default=1,
            ),
        ),
    ]
